hmcts/rd-profile-sync

- README.md
- build.gradle
- src/main/java/uk/gov/hmcts/reform/profilesync/controller/SyncController.java
- src/main/java/uk/gov/hmcts/reform/profilesync/domain/UserProfile.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/ProfileSyncService.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/ProfileUpdateService.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/UserAcquisitionService.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/UserAcquisitionServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/profilesync/controller/SyncControllerTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/helper/MockDataProvider.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/ProfileSyncServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/ProfileSyncServiceTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/UserAcquisitionServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/util/JsonFeignResponseHelperTest.java
> Rdcc 237 2 Enabling pitest coverage

- src/test/java/uk/gov/hmcts/reform/profilesync/client/IdamClientTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/config/FeignConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/config/ServiceTokenGeneratorConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/config/TokenConfigPropertiesTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/controller/SyncControllerTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/domain/CreateUserProfileResponseTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/domain/GetUserProfileResponseTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/domain/UserProfileTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/helper/MockDataProvider.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/UserAcquisitionServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/util/JsonFeignResponseHelperTest.java
> RDCC-237 renamed test methods and added unit test coverage

- .githooks/pre-push
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDCC-237
Change description
Spring Boot schedular job to update the userprofile status from idam for every hour.
```
[ ] Yes
[ ] No
```
> RDCC-237-Quarz:githooks added to sync job

- infrastructure/main.tf
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDCC-237
Change description
Spring Boot schedular job to update the userprofile status from idam for every hour.
```
[ ] Yes
[ ] No
```
> RDCC-237-Quarz:removed CCD urls from main.tf

- web.config
Fix for deploying the jar
```
[ ] Yes
[ X] No
```
> Fix for the AAT build

- src/smokeTest/java/uk/gov/hmcts/reform/profilesync/SmokeTest.java
Fix for smoke test
```
[ ] Yes
[X ] No
```
> Fixing smoke test

- security.sh
Fix for security scan
```
[ ] Yes
[ X] No
```
> Adding file to fix security scan within nightly build

- Jenkinsfile_nightly
Fixing the test url for security scan
```
[ ] Yes
[X ] No
```
> Fixing the Test url for security scan

- Jenkinsfile_nightly
- infrastructure/main.tf
- security.sh
Build changes. Client id and secret to picked up from the vault.
```
[ ] Yes
[ X] No
```
> Security build fix

- infrastructure/main.tf
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/profilesync/util/UserProfileSyncJobScheduler.java
- src/main/resources/application.yaml
code committed to pick the cron schedule time from config file
```
[ ] Yes
[X ] No
```
> RDCC-rsync: code committed to pick the changes from config file

- src/main/java/uk/gov/hmcts/reform/profilesync/util/UserProfileSyncJobScheduler.java
No Jira
removed date from scheduler class log.
```
[ ] Yes
[X ] No
```
> sonarcubefix for build fail

- src/integrationTest/resources/application.yaml
integration test case issue fixed
```
[ ] Yes
[ X] No
```
> sonarcubefix:integration test case issue fixed

- build.gradle
sonar qube failed in jenkins build
```
[ ] Yes
[X ] No
```
> sonarfix issue fixed

- .githooks/pre-push
- Jenkinsfile_CNP
- build.gradle
- src/main/java/uk/gov/hmcts/reform/profilesync/domain/UserProfile.java
- src/main/java/uk/gov/hmcts/reform/profilesync/domain/UserProfileResponse.java
- src/test/java/uk/gov/hmcts/reform/profilesync/util/JsonFeignResponseHelperTest.java
https://tools.hmcts.net/jira/browse/RDCC-457
code committed to generate pi report in jenkins
```
[ ] Yes
[X ] No
```
> sonarfix:code committed to verify the pitest report in the PR

- src/test/java/uk/gov/hmcts/reform/profilesync/service/ProfileSyncServiceImplTest.java
> Fixing pitest

- Jenkinsfile_CNP
code committed to enable build .
```
[ ] Yes
[ X] No
```
> removed pipeline step to deploy in prod

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RDCC-478
```
[ ] Yes
[ ] No
```
> disable AAT deploy

- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/values.yaml
https://tools.hmcts.net/jira/browse/RDCC-478
```
[ ] Yes
[ ] No
```
> Ingress patch

- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/variables.tf
> Adding latest AKS changes for arse

- build.gradle
> Bump Reform health starter

- build.gradle
- src/main/java/uk/gov/hmcts/reform/profilesync/config/SecurityConfiguration.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/UserAcquisitionServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/profilesync/util/UserProfileSyncJobScheduler.java
- src/test/java/uk/gov/hmcts/reform/profilesync/client/IdamClientTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/config/AuthCheckerConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/config/TokenConfigPropertiesTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/ProfileSyncEnumTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/util/UserProfileSyncJobSchedulerTest.java
PARENT: https://tools.hmcts.net/jira/browse/RDCC-647
CHILD   : https://tools.hmcts.net/jira/browse/RDCC-651
Remove logging of sensitive keys and Client identifying data
**Does this PR introduce a breaking change?** (check one with " ❌")
```
[ ] Yes
[ ❌] No
```
> RDCC-653 : Remove logging of sensitive keys and client identifying data

- audit.json
- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/values.preview.template.yaml
- security.sh
https://tools.hmcts.net/jira/browse/RDCC-682
> RDCC-682 security fix, aks deploy fix

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-682
> dependancy error fix

- Jenkinsfile_nightly
- audit.json
- build.gradle
- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/values.preview.template.yaml
- config/owasp/suppressions.xml
- security.sh
https://tools.hmcts.net/jira/browse/RDCC-682
> RDCC-682 nightly build fix

- src/main/java/uk/gov/hmcts/reform/profilesync/service/ProfileSyncService.java
- src/main/java/uk/gov/hmcts/reform/profilesync/util/UserProfileSyncJobScheduler.java
https://tools.hmcts.net/jira/browse/RDCC-768
> RDCC-768 - Fixing Sonar issues

- build.gradle
Fix sonar changes suggested by DevOps
```
[ ] Yes
[X] No
```
> Prod sonar fix

- config/owasp/suppressions.xml
RDCC-958
fixing the issue for suppression
```
[ ] Yes
[X ] No
```
> Fix suppression issue

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/profilesync/RunProfileSyncJobTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/profilesync/SpringBootIntegrationTest.java
Moving changes from https://github.com/hmcts/rd-profile-sync/pull/183 into Demo
> RDCC-863: moving changes from Master to Demo

- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImpl.java
RDCC-1082
adding loggers
```
[ ] Yes
[ X] No
```
> logger updated

- charts/rd-profile-sync/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-1333
Updated charts version to 0.0.8
```
[ ] Yes
[X] No
```
> Updated charts version to 0.0.8

- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/values.yaml
https://tools.hmcts.net/jira/browse/RDCC-1333
Added env variables and bumped chart version to 0.0.5
```
[ ] Yes
[X] No
```
> Demo rdcc 1333 helm version updates

- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/values.demo.template.yaml
- charts/rd-profile-sync/values.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-1333
Added env vars and bumped up chart version to 0.0.5
```
[ ] Yes
[X] No
```
> Added env vars and bumped up chart version to 0.0.5

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-1440
removing installCharts() from Jenkinsfiles
```
[ ] Yes
[x] No
```
> RDCC-1440, Master: removing installCharts() from Jenkinsfiles

- build.gradle
- config/owasp/suppressions.xml
Removed Suppression and added modified build.gradle
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDCC-1308
Change description
Removed Suppression and added modified build.gradle
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[ X] No
> Removed Suppression and added modified build.gradle(Not to  merge)

- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/values.yaml
- infrastructure/main.tf
RDCC-1034
feat: removed unused entries from values.yaml and main.tf file
```
[ ] Yes
[ X] No
```
> feat: removed unused entries from values.yaml and main.tf file

- Jenkinsfile_nightly
RDCC-1464
RDCC-1464 - removed functional test cases for nightly build
```
[ ] Yes
[X] No
```
> fix: RDCC-1464 - removed functional test cases for nightly build

- config/owasp/suppressions.xml
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDCC-1646
```
[ ] Yes
[X] No
```
> Added missing App Insights Instrumentation Key

- src/integrationTest/resources/application.yaml
- src/main/java/uk/gov/hmcts/reform/profilesync/schedular/UserProfileSyncJobScheduler.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/UserAcquisitionServiceImpl.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/profilesync/schedular/UserProfileSyncJobSchedulerTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/UserAcquisitionServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/util/UserProfileSyncJobSchedulerTest.java
**JIRA link (if applicable)**
https://tools.hmcts.net/jira/browse/RDCC-1581
**Change description**
Bringing changes from https://github.com/hmcts/rd-profile-sync/pull/277
```
[ ] Yes
[x] No
```
> RDCC-1581, Demo: Adding component name to all application logs

- src/integrationTest/resources/application.yaml
- src/main/java/uk/gov/hmcts/reform/profilesync/schedular/UserProfileSyncJobScheduler.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/UserAcquisitionServiceImpl.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/UserAcquisitionServiceImplTest.java
**JIRA link (if applicable)**
https://tools.hmcts.net/jira/browse/RDCC-1581
**Change description**
Adding component name to all application logs, bringing changes from Demo PR (https://github.com/hmcts/rd-profile-sync/pull/279)
```
[ ] Yes
[x] No
```
> RDCC-1581: bringing changes from Demo

- src/integrationTest/java/uk/gov/hmcts/reform/profilesync/AuthorizationEnabledIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/profilesync/RunProfileSyncJobIntTest.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImpl.java
RDCC-1604
feat: adding new integration test cases for new functionality
```
[ ] Yes
[ X] No
```
> feat: adding new integration test cases for new functionality

- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/values.yaml
https://tools.hmcts.net/jira/browse/RDCC-1806
```
[ ] Yes
[X] No
```
> Added env vars and bumped up chart version

- src/main/java/uk/gov/hmcts/reform/profilesync/schedular/UserProfileSyncJobScheduler.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/UserAcquisitionServiceImpl.java
feat: updating  loggers
```
[ ] Yes
[X ] No
```
> feat: updating  loggers

- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/profilesync/RunProfileSyncJobIntTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/profilesync/SmokeTest.java
Fixing serenity report for filtering Integration and Smoke tests
```
[] Yes
[X] No
```
> Fixing serenity report for filtering Integration and Smoke tests

- infrastructure/state.tf
Fixing terraform state file
```
[ ] Yes
[X] No
```
> Fixing terraform

- src/smokeTest/java/uk/gov/hmcts/reform/profilesync/SmokeTest.java
RDCC-835
Fixing SmokeTest test for serenity report
```
[ ] Yes
[X] No
```
> Fixing SmokeTest test for serenity report

- src/main/java/uk/gov/hmcts/reform/profilesync/domain/ProfileSyncAudit.java
- src/main/java/uk/gov/hmcts/reform/profilesync/domain/ProfileSyncAuditDetails.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImpl.java
https://tools.hmcts.net/jira/browse/RDCC-1851
Nighlty build fix 1
```
[ ] Yes
[X] No
```
> Nighlty build fix 1

- build.gradle
- src/contractTest/java/uk/gov/hmcts/reform/profilesync/IdamConsumerTest.java
RDCC-1562
feat:removing search api pact test
```
[ ] Yes
[X ] No
```
> feat:removing search api pact test

- build.gradle
RDCC-1876
This PR covers the version bump ups in Profile Sync
```
[ ] Yes
[X] No
```
> Bump ups: Profile Sync Bump ups(RDCC-1876)

- build.gradle
RDCC-1876
This PR covers all the bump up versions in Profile Sync
```
[ ] Yes
[ X] No
```
> Bump : Bump ups library versions(RDCC-1876)

- build.gradle
(RDCC-1933)
This PR covers the jar bump up versions
```
[ ] Yes
[X ] No
```
> Bumpups : Bump up jar version including owasp(RDCC-1933)

- config/owasp/suppressions.xml
feat:suppressing the CVE to make build green in the master
```
[ ] Yes
[X] No
```
> feat:adding suppressions for the build failures

- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/requirements.yaml
https://tools.hmcts.net/jira/browse/RDCC-2021
```
[ ] Yes
[X] No
```
> Update java chart and bump chart version

- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/requirements.yaml
https://tools.hmcts.net/jira/browse/RDCC-2021
Bringing changes from Master
```
[ ] Yes
[x] No
```
> RDCC-2021, PerfTest: Bringing changes from Master

- src/main/java/uk/gov/hmcts/reform/profilesync/schedular/UserProfileSyncJobScheduler.java
https://tools.hmcts.net/jira/browse/RDCC-2072
Same changes as: https://github.com/hmcts/rd-profile-sync/pull/426 - adding 'pui-caa' to search query
```
[ ] Yes
[x] No
```
> RDCC-2072, Demo: adding 'pui-caa' to search query

- src/main/java/uk/gov/hmcts/reform/profilesync/schedular/UserProfileSyncJobScheduler.java
https://tools.hmcts.net/jira/browse/RDCC-2072
adding 'pui-caa' to search query
```
[ ] Yes
[x] No
```
> RDCC-2072: adding 'pui-caa' to search query

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RDCC-2073
```
[ ] Yes
[X] No
```
> Add sync branch method call

- build.gradle
RDCC-2017
This PR deals with the Jar version upgrade created by Bot
```
[ ] Yes
[ X] No
```
> Bump Up : RDCC-2017 Address Jar version upgrades

- Dockerfile
- README.md
- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/values.preview.template.yaml
- charts/rd-profile-sync/values.yaml
- infrastructure/main.tf
- src/integrationTest/resources/application.yaml
- src/main/java/uk/gov/hmcts/reform/profilesync/config/ServiceTokenGeneratorConfiguration.java
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDCC-2141
```
[ ] Yes
[X] No
```
> Update s2s secret references

- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImpl.java
Not Applicable
Add loggers around IDAM calls.
```
[ ] Yes
[x] No
```
> (feat): Add loggers around IDAM calls.

- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/values.preview.template.yaml
- charts/rd-profile-sync/values.yaml
- src/integrationTest/java/uk/gov/hmcts/reform/profilesync/AuthorizationEnabledIntTest.java
- src/integrationTest/resources/application.yaml
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/profilesync/util/JsonFeignResponseUtil.java
- src/main/resources/bootstrap.yaml
- src/test/java/uk/gov/hmcts/reform/profilesync/advice/UserProfileSyncExceptionTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/config/ServiceTokenGeneratorConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/domain/ProfileSyncAuditDetailsIdTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/repository/ProfileSyncAuditDetailsRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/UserAcquisitionServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/util/JsonFeignResponseUtilTest.java
https://tools.hmcts.net/jira/browse/RDCC-2067
```
[ ] Yes
[x] No
```
> RDCC-2067: Referring to New S2S Secret & Addressing All Sonar Issues in Master

- build.gradle
- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/requirements.yaml
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/UserAcquisitionServiceImpl.java
RDCC-2507
This change upgrade the Jar versions
```
[ ] Yes
[X ] No
```
> DependBot: Upgrade Jar versions(RDCC- 2507)

- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/values.preview.template.yaml
- charts/rd-profile-sync/values.yaml
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDCC-2505
```
[ ] Yes
[X] No
```
> Update app insights key secret name

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-1985
removing unwanted suppressions
```
[ ] Yes
[x] No
```
> RDCC-1985: removing unwanted suppressions

- charts/rd-profile-sync/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-2746
Helm version updated
```
[ ] Yes
[ X] No
```
> fix:RDCC-2746-Helm chart version updated

- Jenkinsfile_nightly
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDCC-2900
Change description
Nightly build missing security scan step and reports added
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X] No
> RDCC-2900 Nightly jenkins script changes done to enable security scan

- src/main/resources/application.yaml
Removed unwanted variables
```
[ ] Yes
[X] No
```
> Remove unwanted variables

- src/integrationTest/resources/application.yaml
- src/main/resources/application.yaml
RDCC-373
clean up local variables
```
[ ] Yes
[X] No
```
> clean up local variables

- security.sh
> updated order of command in security.sh to fix security scan

- build.gradle
RDCC-3141
This change will address the CVE 2021-33037
```
[ ] Yes
[ X] No
```
> fix : Fix CVE-2021-33037(RDCC-3141)

- build.gradle
RDCC-3150
This change is to remove the bintray reference
```
[ ] Yes
[ X] No
```
> fix : remove bintray reference(RDCC-3150)

- charts/rd-profile-sync/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-3169
RDCC-3169 - Update chart versions in all PRD repos
```
[ ] Yes
[X] No
```
> RDCC-3169 - Update chart versions in all PRD repos

- charts/rd-profile-sync/values.yaml
- config/owasp/suppressions.xml
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDCC-3507
Create a postgres v11 DB
```
[ ] Yes
[X] No
```
> RDCC-3507: Create a v11 Postgres DB - Demo

- build.gradle
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDCC-3557
Added postgresql_version and fixed CVE CVE-2021-22096
```
[ ] Yes
[x] No
```
> fix: Added postgresql_version and fixed CVE CVE-2021-22096

- infrastructure/main.tf
Updating DB Secrets #739
```
[ ] Yes
[x] No
```
> Updating DB Secrets

- infrastructure/main.tf
Updating DB Secrets
```
[ ] Yes
[x] No
```
> Profile Sync PerfTest: Updating DB Secrets

- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/values.aat.template.yaml
- charts/rd-profile-sync/values.yaml
- infrastructure/main.tf
https://tools.hmcts.net/confluence/display/RSTR/CHG5006041+-+PRD+and+AM+Postgress+Databases+Upgrade+to+v11+Release+Implementation+Plan
```
[ ] Yes
[X] No
```
> Update configurations to point to v1 DB

- src/integrationTest/resources/application.yaml
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImpl.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImplTest.java
https://tools.hmcts.net/jira/browse/RDCC-3559
_Enhancing logic to increase number of users fetched from IDAM_
```
[ ] Yes
[x] No
```
> RDCC-3559: Enhancing logic to increase number of users fetched from IDAM

- Jenkinsfile_nightly
- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-3782
Collating Dependabot PRs
```
[ ] Yes
[x] No
```
> RDCC-3782: Collating dependabot PRs

- build.gradle
- config/owasp/suppressions.xml
- gradle/wrapper/gradle-wrapper.properties
> Rdcc 3945 newfix

- src/test/java/uk/gov/hmcts/reform/profilesync/config/ServiceTokenGeneratorConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/domain/ProfileSyncAuditTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/repository/ProfileSyncAuditDetailsRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImplTest.java
https://tools.hmcts.net/jira/browse/RDCC-3462
Address remaining Sonar issues in Ref Data repos
```
[ ] Yes
[ X] No
```
> fixed sonar issues issues

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4048
CVE Fixes
```
[ ] Yes
[x] No
```
> RDCC-4048: CVE Fixes

- charts/rd-profile-sync/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-4056
fix: Bump base java helm chart to 3.7.1 
```
[ ] Yes
[x] No
```
> fix: Bump base java helm chart to 3.7.1

- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/UserAcquisitionServiceImplTest.java
https://tools.hmcts.net/jira/browse/RDCC-4041
Sync: Completeness of functional and Integration test
```
[ ] Yes
[X] No
```
> Sync-Completeness of functional and Integration test

- charts/rd-profile-sync/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-4139
Updated java chart version to 3.7.3
```
[ ] Yes
[x] No
```
> fix: Updated java chart version to 3.7.3

- src/main/java/uk/gov/hmcts/reform/profilesync/schedular/UserProfileSyncJobScheduler.java
https://tools.hmcts.net/jira/browse/RDCC-4279
- Added cwd-user in the search query
```
[ ] Yes
[x] No
```
> fix: RDCC-4279: Added cwd-user in the search query

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4299
Collating DependaBot PRs
```
[ ] Yes
[x] No
```
> RDCC-4300: Collating DependaBot PRs

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4331
```
[ ] Yes
[X] No
```
> RDCC-4331 Profile Sync Nightly build issue

- build.gradle
cve fix for spring core
```
[ ] Yes
[X] No
```
> CVE FIX for spring core

- renovate.json
*### JIRA link  ###
https://tools.hmcts.net/jira/browse/RDCC-4821
Configured renovate
```
[ ] Yes
[x] No
```
> config: RDCC-4821 Configured renovate

- .github/workflows/combine-prs.yml
https://tools.hmcts.net/jira/browse/RDCC-4858
```
[ ] Yes
[X] No
```
> config: RDCC-4858 added git hub workflow to auto merge renovate PRs

- .github/workflows/combine-prs.yml
https://tools.hmcts.net/jira/browse/RDCC-4858
```
[ ] Yes
[X] No
```
> RDCC-4858:ProfileSync Automerge Renovate PR's

- .github/dependabot.yml
https://tools.hmcts.net/jira/browse/RDCC-4946
Deleted dependabot yaml file as Renovate changes are already in place to upgrade the dependencies automatically
```
[ ] Yes
[x] No
```
> RDCC-4946  Delete dependabot yaml file

- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDCC-5049
Upgrade java chart 
```
[ ] Yes
[x] No
```
> RDCC-5049 Upgrade java chart 

- charts/rd-profile-sync/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-5145
Upgrade java chart version
```
[ ] Yes
[x] No
```
> RDCC-5145 Upgrade java chart version

- config/owasp/suppressions.xml
> Address CVE-2020-23171 for all refdata REPOs

- build.gradle
Upgrade Idam client Upgrade
```
[ ] Yes
[X] No
```
> Idam client Upgrade

- src/main/resources/application.yaml
Disable ApacheHTTP
```
[ ] Yes
[X] No
```
> Disable ApacheHTTPClient

- src/main/resources/application.yaml
Reverts hmcts/rd-profile-sync#676
> Revert "Disable ApacheHTTPClient"

- src/main/resources/application.yaml
Enable okhttpclient
```
[ ] Yes
[X] No
```
> Rdcc apache disable

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-5534
Upgrading `snakeyaml` to fix CVE-2022-38752
```
[ ] Yes
[x] No
```
> RDCC-5534: Upgrading `snakeyaml`

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- charts/rd-profile-sync/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-5931
```
[ ] Yes
[X] No
```
> Replace after with afterSuccess for depreciated : RDCC-5931

- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImpl.java
https://tools.hmcts.net/jira/browse/RDCC-6295
Address fortify issues in Profile Sync Repository
```
[ ] Yes
[x] No
```
> RDCC-6295 Address fortify issues in Profile Sync Repository

- charts/rd-profile-sync/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-1707
Upgraded helm chart version to `4.0.11`
```
[ ] Yes
[x] No
```
> RDCC-1707: Upgrade helm chart version to latest

- charts/rd-profile-sync/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-6374
Upgrading chart version to `4.0.13`
```
[ ] Yes
[x] No
```
> RDCC-6374: Upgrading chart version to 4.0.13

- Dockerfile
- build.gradle
- charts/rd-profile-sync/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-6328
Profile Sync API Spring boot upgrade
```
[ ] Yes
[x ] No
```
> Feat:Profile Sync API Spring boot upgrade

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-6597
Upgrade lib
```
[ ] Yes
[x] No
```
> Upgrade lib

- audit.json
https://tools.hmcts.net/jira/browse/DTSRD-213
```
[ ] Yes
[X] No
```
> DTSRD-213 - add ignore to audit.json for 10096_Timestamp

- src/integrationTest/java/uk/gov/hmcts/reform/profilesync/SpringBootIntTest.java
https://tools.hmcts.net/jira/browse/RDCC-6746
[RDCC-6746]upgrade deprecated methods to java 17
```
[ ] Yes
[x ] No
```
> [RDCC-6746]upgrade deprecated methods to java 17

- build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-550
fix CVE-2023-20883
```
[ ] Yes
[x] No
```
> DTSRD-550: fix CVE-2023-20883

- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/values.yaml
- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/profilesync/AuthorizationEnabledIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/profilesync/RunProfileSyncJobIntTest.java
- src/integrationTest/resources/application.yaml
- src/main/java/uk/gov/hmcts/reform/profilesync/client/CaseWorkerRefApiClient.java
- src/main/java/uk/gov/hmcts/reform/profilesync/domain/CaseWorkerProfile.java
- src/main/java/uk/gov/hmcts/reform/profilesync/schedular/UserProfileSyncJobScheduler.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImpl.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/profilesync/domain/CaseWorkerProfileTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/helper/MockDataProvider.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImplTest.java
https://tools.hmcts.net/jira/browse/RDCC-6762
[RDCC-6762]Update profileSync job to sync data between IDAM and SRD
```
[ ] Yes
[ x] No
```
> [RDCC-6762]Update profileSync job to sync data between IDAM and SRD

- src/integrationTest/java/uk/gov/hmcts/reform/profilesync/RunProfileSyncJobIntTest.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/profilesync/domain/CaseWorkerProfileTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImplTest.java
https://tools.hmcts.net/jira/browse/RDCC-6762
Rdcc 6762 -fix cwd user failure
```
[ ] Yes
[ x] No
```
> Rdcc 6762 -fix cwd user failure

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSRD-175
remove suppression
```
[ ] Yes
[x] No
```
> DTSRD-175: remove suppression

- build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-660
Remedy for CVE-2023-2976
```
[ ] Yes
[x] No
```
> Update guava to 32.0.1

- src/integrationTest/java/uk/gov/hmcts/reform/profilesync/AuthorizationEnabledIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/profilesync/RunProfileSyncJobIntTest.java
- src/main/java/uk/gov/hmcts/reform/profilesync/client/CaseWorkerRefApiClient.java
- src/main/java/uk/gov/hmcts/reform/profilesync/domain/response/GetCaseWorkerProfileResponse.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/CaseWorkerAcquisitionService.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/CaseWorkerAcquisitionServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/profilesync/domain/response/GetCaseWorkerProfileResponseTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/helper/MockDataProvider.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/CaseWorkerAcquisitionServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImplTest.java
https://tools.hmcts.net/jira/browse/RDCC-6802
[RDCC-6802]Profile Sync to verify if user exists in the SRD
```
[ ] Yes
[ x] No
```
> [RDCC-6802]Profile Sync to verify if user exists in the SRD

- lib/applicationinsights.json
app insights fix
```
[ ] Yes
[ x] No
```
> testing app insights

- lib/applicationinsights.json
App insights fix
```
[ ] Yes
[ X] No
```
> App insights fix

- src/integrationTest/resources/application.yaml
- src/main/resources/application.yaml
Increase in Page size to fix prod sync issue
```
[ ] Yes
[ x] No
```
> Increase in Page size to fix prod sync issue

- src/integrationTest/resources/application.yaml
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RDCC-6898
[RDCC-6898]Populate option to see Profile sync log in Azure Portal
```
[ ] Yes
[ x] No
```
> [RDCC-6898]Populate option to see Profile sync log in Azure Portal

- build.gradle
- config/owasp/suppressions.xml
> CVE suppression CVE-2023-34034

- .github/renovate.json
- build.gradle
- Updating renovate config.
- Updating reform logging.
https://tools.hmcts.net/jira/browse/DTSRD-1224
```
[ ] Yes
[x] No
```
> DTSRD-1224

- config/owasp/suppressions.xml
> suppression CVE-2023-5072

- audit.json
- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
> DTSRD-1629 . provisioning flexi server fro rd-profile-sync

- audit.json
- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
> Dtsrd 1629- running perftest

- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
> provisioning V15 demo server

- src/main/resources/application.yaml
> Update application.yaml. fixing connection string

- src/main/resources/application.yaml
> Update application.yaml. revertign changes to connection string

- audit.json
> DTSRD-1173-1.adding Zaproxy fix

- src/main/resources/application.yaml
> default_schema

- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
> DTSRD-1793.migrating demo from V11 to V15

- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
> DTSRD-1793.migrating perftest from V11 to V15

- Jenkinsfile_CNP
- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
- src/main/resources/application.yaml
> Dtsrd 1253

- build.gradle
- config/owasp/suppressions.xml
- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
- src/main/resources/application.yaml
> Migrate rd perftest to v16

- Jenkinsfile_CNP
- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
> DTSRD-1893.Upgrading main branch to V16 and adding subnet_suffix

- Jenkinsfile_CNP
- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/values.preview.template.yaml
- charts/rd-profile-sync/values.yaml
- src/integrationTest/java/uk/gov/hmcts/reform/profilesync/RunProfileSyncJobIntTest.java
- src/main/java/uk/gov/hmcts/reform/profilesync/client/IdamClient.java
- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImpl.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImplTest.java
> DTSRD-2395: Fix Profile sync issue

- infrastructure/main.tf
> force user permissions

- src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImpl.java
> Remove logging

- build.gradle
> Update build.gradle. Fix Pit test

- charts/rd-profile-sync/Chart.yaml
- charts/rd-profile-sync/values.yaml
> Disable spot instances

- Jenkinsfile_CNP
- infrastructure/main.tf
> Delete single server from demo

- Jenkinsfile_CNP
- infrastructure/main.tf
- infrastructure/terraform.tf
> Dtspo 16369

- Jenkinsfile_CNP
- infrastructure/main.tf
- infrastructure/terraform.tf
> Dtspo 16369 - delete single server

- Jenkinsfile_CNP
- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/terraform.tf
> DTSPO-16369

- Jenkinsfile_CNP
> Update Jenkinsfile_CNP - syncing demo with master

- infrastructure/terraform.tf
> Version upgrade azurerm

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSRD-2802
- updated idam-java-client to 3.0.3
- updated openfeign to 3.1.9
> DTSRD-2802

- build.gradle
> fix PiTest issues

- src/main/resources/application.yaml
> Fix flyway schema issues on ithc

- build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-3025
> Removed deprecated library

- build.gradle
> Update build.gradle. Fix Build

- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/DTSRD-3316
Resources decommission
> decommission profile-sync resources
